name: Deploy to EC2 back instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set gradlew executable
        run: chmod +x backend/gradlew
        
#      - name: Backend Test
#        run: |
#          cd backend
#          ./gradlew clean build -x test

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/devmatch
            git pull origin main
            cd backend
            chmod +x gradlew
            ./gradlew clean build -x test --no-daemon
            PID=$(pgrep -f 'backend-0.0.1-SNAPSHOT.jar') && kill -9 $PID || echo "No process found"
            nohup java -jar build/libs/backend-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
            
